name: Build and Deploy Hugo Site

on:
  push:
    branches:
      - main  # 或者你使用的是哪个分支

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source code
      uses: actions/checkout@v2
      with:
        repository: 'hanzhongzi/hanzhongzi.github.io_hugo_sourcecode'
        path: 'source_code'

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: 'latest'

    - name: Build Hugo site
      run: cd hanzhongzigithubio ;hugo --config hugo.yaml
      working-directory: ./source_code

    - name: Checkout public repository
      uses: actions/checkout@v2
      with:
        repository: 'hanzhongzi/hanzhongzi.github.io'
        path: 'public_repo'

    - name: Copy public directory to public repository
      working-directory: ./source_code
      run: |
        pwd;ls -lha ;cp -afR hanzhongzigithubio/public/* ../public_repo/

    - name: Use secret as part of a command
      env:
       MY_SECRET: ${{ secrets.ACCESS_TOKEN }}
      run: |
       # 使用Secret作为命令的一部分而不直接打印它
       echo  $MY_SECRET


    - name: Commit and Push changes
      run: |
        cd public_repo
        git add .
        git commit -m "Automated deployment: $(date +'%Y-%m-%d %H:%M:%S')"
        git config user.name github-actions
        git config user.email github-actions@github.com
        cd ..

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
          personal_token: ${{ secrets.ACCESS_TOKEN }}
          external_repository: hanzhongzi/hanzhongzi.github.io
          publish_dir: ./public_repo
          publish_branch: main
